### ISSUE TITLE
No wifi access point

### ISSUE THREAD

**Issue by DualByte** [mame82/P4wnP1_aloa#105]
I dont anything why it doesnt work

**Comment by lukespademan** [comment]
I am also having issues. I have flashed 0.1.0-alpha2 using win32 disk imager and after waiter for 5mins none of my devices have detected any beacon frames (network does not appear in list). I am using:
* Raspberry Pi Zero w V1.1
* sandisk Ultra 16GB class 10 micro SD card

@DualByte is this what you are also experiencing? Can you please give any other infomation about your issues to improve the chances of this being resoled.

**Comment by DualByte** [comment]
> I am also having issues. I have flashed 0.1.0-alpha2 using win32 disk imager and after waiter for 5mins none of my devices have detected any beacon frames (network does not appear in list). I am using:
> 
> * Raspberry Pi Zero w V1.1
> * sandisk Ultra 16GB class 10 micro SD card
> 
> @DualByte is this what you are also experiencing? Can you please give any other infomation about your issues to improve the chances of this being resoled.

I am having the same probmen and Im actually using even the same SD card as you. I dont know anything why it wouldn't work.

**Comment by HighSchoolDude** [comment]
@DualByte  I doubt this would be causing the problem but have you tried using a different ISO software like Etcher, or Rufus?

**Comment by DualByte** [comment]
> @DualByte  I doubt this would be causing the problem but have you tried using a different ISO software like Etcher, or Rufus?

No I have not actually tried that. I will try it shortly

**Comment by Swiftb0y** [comment]
I didn't have a good experience with Etcher. I recommend Rufus on Windows or just plain old dd on macOS and Linux.

**Comment by DualByte** [comment]
> @DualByte I doubt this would be causing the problem but have you tried using a different ISO software like Etcher, or Rufus?

Rufus didnt work, either win32diskimager or etcher was working.

**Comment by lukespademan** [comment]
I used etcher and it now works :)

**Comment by DualByte** [comment]
I didnt get it to work

**Comment by lukespademan** [comment]
Have you tried using etcher? Do you have a different microSD you can try?

**Comment by DualByte** [comment]
> Have you tried using etcher? Do you have a different microSD you can try?

I have tried and also have tried using other systems like raspbian, ubuntu mate but it have not show the wlab0 interface and it has been working before but not anymore.

**Comment by lukespademan** [comment]
Is it a pi zero or pi zero w?

**Comment by DualByte** [comment]
> Is it a pi zero or pi zero w?

It is pi zero w

**Comment by lukespademan** [comment]
This sounds like a hardware issue and is outside the scope of this project. I can advise you look at the raspberry pi forums for advice :)

**Comment by DualByte** [comment]
> This sounds like a hardware issue and is outside the scope of this project. I can advise you look at the raspberry pi forums for advice :)

Okay. Thanks for the help.
