### ISSUE TITLE
“No Internet” (unable to connect to wi-fi)

### ISSUE THREAD

**Issue by BBQRIBS72** [mame82/P4wnP1_aloa#107]
I can see the P4wnP1 WiFi and I can enter in the passcode and it accepts it. However, there is no internet connection and this means I cannot ssh into the P4wnP1 or run payloads. 

Not sure what the problem is.

I have changed my Regulatory domain to GB as I am based in England. The channel is still the default 6.

Thank you.

**Comment by mame82** [comment]
No need for Internet. SSH target host is 172.24.0.1 for WiFi, 172.16.0.1
for Ethernet over USB and 172.26.0.1 for Bluetooth NAP

BBQRIBS72 <notifications@github.com> schrieb am So., 19. Mai 2019, 13:45:
