### ISSUE TITLE
Caps Lock Problem

### ISSUE THREAD

**Issue by ryanpoh** [mame82/P4wnP1_aloa#135]
For some reason, when the script runs, it runs with "CAPS" button pressed. Which cause words like "WindowsBase" to be "wINDOWSbASE" which causes errors when running the HID.

I have tried just adding press("CAPS") right after powershell opens with (GUI + r), however the solution isn't stable. It works sometimes, and sometimes it doesn't. How do you recommend I go about this?

**Comment by mame82** [comment]
Is CAPS LOCK enabled by the script itself?

Can you post details on the HIDScript you are using.

Which language layout is in use?

**Comment by ryanpoh** [comment]
Hi mame82, thanks for the reply! However, it is solved. It was all good after restarting the computer. 

Thanks again!
