### ISSUE TITLE
Trouble with USB mass storage emulation

### ISSUE THREAD

**Issue by RancidRocket** [mame82/P4wnP1_aloa#170]
When i run the test image, or any image for that matter, no drive mounts.
I am using a data capable line and a data capable port. 
I do not know what is happening.
Please help!

**Comment by 21weberer** [comment]
Have you tried mutlipule cables?

**Comment by RancidRocket** [comment]
I have, it just turns out that every single cable in the house has no data lines.
Go figure

**Comment by 21weberer** [comment]
of course, that is how it works. i have been there. my other solution is to harvest the usb male head from a spare cable and solder the head onto the pi, if that is a possible thing to do in your situation.

**Comment by RancidRocket** [comment]
thank you! i got a cable now, but that sounds really cool. im gonna go try it
