### ISSUE TITLE
Problem with web interface (no webserver)

### ISSUE THREAD

**Issue by RancidRocket** [mame82/P4wnP1_aloa#175]
attempting to connect to the webserver at 172.24.0.1:8000 through firefox yields this error message

An error occurred during a connection to 172.24.0.1:8000. SSL received a record that exceeded the maximum permissible length. Error code: SSL_ERROR_RX_RECORD_TOO_LONG 

attempting to connect to 172.24.0.1:8000 through chrome yields this:
ERR_NETWORK_CHANGED

i have no idea what is causing this but it only happens when connecting to the network for the second time, and can be fixed with a reflash, but that is really time consuming.

**Comment by 21weberer** [comment]
Is there any setting you changed in the net interface?

**Comment by RancidRocket** [comment]
i changed the default wifi profile, and that was it.

**Comment by 21weberer** [comment]
the default as in what the master template uses? if so, what template are you using?

**Comment by RancidRocket** [comment]
Just a custom wifi template, I chsnged name and password, Microsoft edge works every time with this, so I’m not sure if it’s that big of a problem anymore

**Comment by RancidRocket** [comment]
Just a custom wifi template, I changed name and password, Microsoft edge works every time with this, so I’m not sure if it’s that big of a problem anymore
