### ISSUE TITLE
ES keyboard not mapped correctly

### ISSUE THREAD

**Issue by SantiCar2** [mame82/P4wnP1_aloa#184]
The Spanish keyboard is not mapped corrctly, when the iput is " ' " the computer recognizes it as a ´ tilde, which ruins the sintax in many powershell commands.

**Comment by SsntiCar2** [comment]
![image](https://user-images.githubusercontent.com/58612159/70362233-35f73600-1852-11ea-8f07-01415cedc20f.png)

**Comment by mame82** [comment]
Can't reproduce the issue, this was typed using "es" layout. Assure your HIDScript uses correct ASCII mapping for `'` as P4wnP1 handles UTF-8 and equal looking characters don't necessarily have same Unicode codepoints

**Comment by mame82** [comment]
The script used to type out the text above:

```
layout('es');			// Spanish keyboard layout
typingSpeed(0,0)

waitLEDRepeat(NUM);		// Wait till NUM LED of target changes frequently multiple times (doesn't work on OSX)
type("Can't reproduce the issue, this was typed using \"es\" layout. Assure your HIDScript uses correct ASCII mapping for")
type(" `'` as P4wnP1 handles UTF-8 and equal looking characters don't necessarily have same Unicode codepoints")
```

It was typed into the browser on Debian with Spanish (es) keyboard layout selected.

**Comment by samu-delucas** [comment]
I have encountered the same issue, although only when using the P4wnP1 in **Windows**. At the moment I use `press("SHIFT 2")` to write `"`, and I still don't know how to write `'`. 

I've found out that this has to do with Windows writting `´` when pressing KEY_APHOSTROPHE and SPACE (`¨` when you also press SHIFT), and Linux writting the correct characters (`' or "`).

**Comment by HectorHumanes** [comment]
Same issue here for Spanish keyboard and Windows
