### ISSUE TITLE
layout

### ISSUE THREAD

**Issue by bodri82** [mame82/P4wnP1_aloa#189]
someone who wants to fix a Swedish layout ?I did not manage to get it together

**Comment by ZaGOnXx** [comment]
I have fixed an swedish layout but i have one key missing the dubbel backslash.

**Comment by bodri82** [comment]
you can post it?

**Comment by osiris6457** [comment]
finnish keymap that you can find in pull requests should be same as swedish.

**Comment by mame82** [comment]
Not sure on Finnish vs Swedish ... gonna test the Finnish layout and add it if at least printable ASCII is working correctly

**Comment by ZaGOnXx** [comment]
I Will upload mine this weekend.
