### ISSUE TITLE
Problem connect to internet raspberry pi zero in windows 7 64 bits with putty

### ISSUE THREAD

**Issue by anduril-glitch** [mame82/P4wnP1_aloa#193]
Hello, 

I tried to connect to the internet my raspberry pi zero with P4wnPI ALOA under windows 7 but when I try to connect in ssh after having put the following ip address 172.16.0.1 ,

But putty tells me "Network Refused".

I don't understand and above all I can't find the "network-only.txt" payload ?

Thank you 

A +

**Comment by anduril-glitch** [comment]
Please, I can't find an answer

**Comment by mame82** [comment]
`172.16.0.1` is reachable if the RNDIS network adapter is working (USB only). So please check your network settings (specifically the configuration of the aforementioned RNDIS adapter).

For a WiFi connection to P4wnP1 ALOA's access point, the default IP is `172.24.0.1`.

`network-only.txt`doesn't apply to P4wnP1 ALOA, this is part of legacy P4wnP1
