### ISSUE TITLE
Changing internet settings

### ISSUE THREAD

**Issue by PineMaster** [mame82/P4wnP1_aloa#195]
It seems that i cannot change my  p4wnp1's internet settings like pass, name etc., it works till i keep my pi plugged in (still quite buggy) and after i disconnect it, it resets to normal state.

**Comment by PineMaster** [comment]
It seems that the whole settings reset when i disconnect
:[

**Comment by osiris6457** [comment]
i had same issue first few times i used p4wnp1 aloa. try restarting or shutting down from web interface or ssh in and try then shutdown/restart. not sure what fixed it for me.

**Comment by PineMaster** [comment]
Ye i tried it but it still doesnt work :[

**Comment by mame82** [comment]
The WiFi network default  settings deployed on boot are stored in templates `wlan0_startup_dhcp_client` and `wlan0_startup_dhcp_client`.

The default WiFi settings deployed on boot are stored in WiFi template `
startup`

Two possible options here, to persist changes (survive reboot):

1. Overwrite the templates mentioned above with alternate settings (caution, if you mess it up it will get hard to undo the changes - so test new settings upfront).
2. Create new templates for alternate settings and modify the `Startup Master Template` in  `GENERIC SETTINGS` tab of the webclient accordingly.
