### ISSUE TITLE
Layout

### ISSUE THREAD

**Issue by bodri82** [mame82/P4wnP1_aloa#51]
Will this project support Swedish layout as p4wnp1? would really be needed ;)

**Comment by Swiftb0y** [comment]
I am currently updating the Official Wiki and considering writing a guide on how you can make your own keyboard mapping...
So while there won't be one made by mame82 (as he would need a Swedish keyboard for Testing), but you will be able with the guide.

**Comment by bodri82** [comment]
Good :)
