### ISSUE TITLE
Cannot connect to P4wnP1 via SSH

### ISSUE THREAD

**Issue by JeromeLC** [mame82/P4wnP1_aloa#77]
I just flashed P4wnP1_aloa and i cannot connect to it via ssh using default pw toor (claims the pw is invalid). I can access the webui fine.

**Comment by mame82** [comment]
Only thing I could imagine is that you haven't used `root` as SSH user, as the pw is indeed `toor`

**Comment by WeinerB0Y** [comment]
You're correct, I was using pi as the user like a moron. Thank you!

**Comment by JeromeLC** [comment]
You're correct. Thanks!
