### ISSUE TITLE
how to add and test keymaps?

### ISSUE THREAD

**Issue by noidea55** [mame82/P4wnP1_aloa#83]
how to add and test keymaps? 

i made FI.json file added it to /root/P4wnP1/dist/keymaps and tried layout('FI') in hidscript but it ignores my request and uses US layout. What i'm doing wrong..? 

_Originally posted by @noidea55 in https://github.com/mame82/P4wnP1_aloa/pull/79#issuecomment-465954503_

**Comment by noidea55** [comment]
SOLVED! correct path is /usr/local/P4wnP1/keymaps

**Comment by bossGovernor2000** [comment]
How did you solve the issue?
